version: '2.0'
services:
  be_retinoid:
    container_name: be_retinoid
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
    volumes:
      - /home/adysaskin/cdn.assets/images:/app/public/img
