module.exports = [
  { name: "Aceh", timeZone: 7, id: "11" },
  { name: "Sumatra Utara", timeZone: 7, id: "12" },
  { name: "Sumatra Barat", timeZone: 7, id: "13" },
  { name: "Riau", timeZone: 7, id: "14" },
  { name: "Kepulauan Riau", timeZone: 7, id: "21" },
  { name: "Kepulauan Bangka Belitung", timeZone: 7, id: "19" },
  { name: "Jambi", timeZone: 7, id: "15" },
  { name: "Bengkulu", timeZone: 7, id: "17" },
  { name: "Sumatra Selatan", timeZone: 7, id: "16" },
  { name: "Lampung", timeZone: 7, id: "18" },
  { name: "Banten", timeZone: 7, id: "36" },
  { name: "DKI Jakarta", timeZone: 7, id: "31" },
  { name: "Jawa Barat", timeZone: 7, id: "32" },
  { name: "Jawa Tengah", timeZone: 7, id: "33" },
  { name: "DI Yogyakarta", timeZone: 7, id: "34" },
  { name: "Jawa Timur", timeZone: 7, id: "35" },
  { name: "Kalimantan Barat", timeZone: 7, id: "61" },
  { name: "Kalimantan Tengah", timeZone: 7, id: "62" },
  { name: "Bali", timeZone: 8, id: "51" },
  { name: "Nusa Tenggara Barat", timeZone: 8, id: "52" },
  { name: "Nusa Tenggara Timur", timeZone: 8, id: "53" },
  { name: "Kalimantan Selatan", timeZone: 8, id: "63" },
  { name: "Kalimantan Timur", timeZone: 8, id: "64" },
  { name: "Kalimantan Utara", timeZone: 8, id: "65" },
  { name: "Sulawesi Utara", timeZone: 8, id: "71" },
  { name: "Gorontalo", timeZone: 8, id: "75" },
  { name: "Sulawesi Tengah", timeZone: 8, id: "72" },
  { name: "Sulawesi Barat", timeZone: 8, id: "76" },
  { name: "Sulawesi Selatan", timeZone: 8, id: "73" },
  { name: "Sulawesi Tenggara", timeZone: 8, id: "74" },
  { name: "Maluku", timeZone: 9, id: "81" },
  { name: "Maluku Utara", timeZone: 9, id: "82" },
  { name: "Papua", timeZone: 9, id: "94" },
  { name: "Papua Barat", timeZone: 9, id: "81" },
];
